shell = "/usr/bin/fish"
import = ["~/.config/alacritty/colours.toml"]

[window]
opacity = 0.8

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Medium" }
size = 13.25

[cursor]
style = { shape = "Beam", blinking = "Never" }
