#!/usr/bin/bash
set -euxo pipefail

THEME="$1"

SWAY="$HOME/.config/sway"
SWAYNC="$HOME/.config/swaync"
WAYBAR="$HOME/.config/waybar"
ROFI="$HOME/.config/rofi"
ALACRITTY="$HOME/.config/alacritty"

test -f "$SWAY/$THEME.conf"
test -f "$SWAYNC/$THEME.css"
test -f "$WAYBAR/$THEME.css"
test -f "$ROFI/$THEME.rasi"
test -f "$ALACRITTY/$THEME.toml"

[[ -L "$SWAY/colours.conf" ]] && unlink "$SWAY/colours.conf"
[[ -L "$SWAYNC/colours.css" ]] && unlink "$SWAYNC/colours.css"
[[ -L "$WAYBAR/colours.css" ]] && unlink "$WAYBAR/colours.css"
[[ -L "$ROFI/colours.rasi" ]] && unlink "$ROFI/colours.rasi"
[[ -L "$ALACRITTY/colours.toml" ]] && unlink "$ALACRITTY/colours.toml"

ln -s "$THEME.conf" "$SWAY/colours.conf"
ln -s "$THEME.css" "$SWAYNC/colours.css"
ln -s "$THEME.css" "$WAYBAR/colours.css"
ln -s "$THEME.rasi" "$ROFI/colours.rasi"
ln -s "$THEME.toml" "$ALACRITTY/colours.toml"
