#!/usr/bin/bash
set -euo pipefail

menuopts() {
    echo "󰤨 WiFi"
	echo "󰂯 Bluetooth"
	echo "󰐥 Power"
	echo "Cancel"
}

CHOICE="$(menuopts | rofi -dmenu -p "󰮫")"

case "$CHOICE" in
    󰤨*) rofi-iwd-menu;;
	󰂯*) rofi-primitive-bt;;
	󰐥*) rofi-power-menu;;
esac
