#!/usr/bin/bash
set -euo pipefail

menuopts() {
	echo "Cancel"
	echo "󰈆 Exit Sway"
	echo "󰐥 Shutdown"
	echo "󰜉 Reboot"
	echo "󰒲 Sleep"
	echo "󰤄 Lock then Sleep"
	echo "󰌾 Lock Screen"
}

CHOICE="$(menuopts | rofi -dmenu -p "󰐥")"

case "$CHOICE" in
	󰈆*) swaymsg exit;;
	󰐥*) systemctl poweroff;;
	󰜉*) systemctl reboot;;
	󰒲*) systemctl suspend;;
	󰤄*)
	    swaylock -d &
        systemctl suspend
	    ;;
	󰌾*) swaylock -d;;
esac
